#!/bin/bash

PID_FILE="/tmp/irs.pid"

start() {
    forever --pidFile $PID_FILE start /opt/image-resize-server/index.js
    RETVAL=$?
}

stop() {
    if [ -f $PID_FILE ]; then
        forever stop /opt/image-resize-server/index.js
        rm -f $PID_FILE
        RETVAL=$?
    else
        echo "image-resize-server not running"
        RETVAL=0
    fi
}

restart() {
    stop
    start
}

status() {
    echo `forever list` | grep -q "/opt/image-resize-server/index.js"
    if ["$?" -eq "0" ]; then
        echo "image-resize-server is running."
        RETVAL=0
    else
        echo "image-resize-server is not running."
        RETVAL=3
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
